### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by WebsByTodd** [mytake/mytake#22]
Check out create-react-app.

```
create-react-app projectName
cd projectName
npm run eject
```
Need to integrate with our project the build script, `projectName/scripts/build.js`.
See also `projectName/src/registerServiceWorker.js`.

**Comment by WebsByTodd** [comment]
Might need to switch away from nunjucks in the long term. Currently webpack creates a [hashed bundle file](https://webpack.github.io/docs/long-term-caching.html). [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) is the webpack plugin to use for getting this hashed bundle into html files, however the nunjucks-loader will not work with html-webpack-plugin. See [this issue](https://github.com/at0g/nunjucks-loader/issues/35).

**Comment by nedtwigg** [comment]
Maybe html-webpack-plugin is heavier-weight than what we need.

[replace-hash](https://www.npmjs.com/package/replace-hash-webpack-plugin) looks at first glance like it could meet our needs.

**Comment by WebsByTodd** [comment]
I gave replace-hash a shot and couldn't get it to work. It's not documented clearly and it's not working as expected. I can get it to grab the source html file and put it in a new location, but it doesn't modify the contents. And the destination location adds intermediate directories, like `/nunjucks/templates/nunjucks/templates/bundle.html`

**Comment by nedtwigg** [comment]
Roger.  Don't worry about this issue, I'll take it.
ᐧ

Ned Twigg
Lead Software Architect, DiffPlug LLC
540-336-8043 (cell)
888-513-6870 (fax)
340 S Lemon Ave #3433, Walnut, CA 91789

**Comment by nedtwigg** [comment]
Netlify does hashing for us.
