### ISSUE TITLE
Style and flesh out "about us" 

### ISSUE THREAD

**Issue by nedtwigg** [mytake/mytake#37]
https://nedtwigg.github.io/mytake/about.html

**Comment by nedtwigg** [comment]
- [ ] find cartoonist to make cartoons for About Us

**Comment by hattersv** [comment]
We have an illustrator in the family (Dave's daughter) that might want to help us out with this.  Her name is Karen Amato and you can see some of her work on her website karenamato.com or on red bubble.  Let me know if I should give her a couple of ideas to work with or if you would like to talk to her directly about that?   She could give us a good price :-)

**Comment by nedtwigg** [comment]
Thanks Victoria!  I've worked with artists before, and the key was to have a really good spec on the technical limitations (aspect ratio requirements, size and color limitations, what the viewer needs to understand after they have seen the image).

I'll get this spec together ASAP and it would be great if Karen could take a look at it to see if she's interested.

**Comment by nedtwigg** [comment]
You can see the current draft of the about-us page here: https://deploy-preview-67--mytake.netlify.com/about/

I threw together these little cartoons because they're easy to edit if we have a better idea later.  If we have an illustrator who's willing to donate a better rendering, we'll definitely accept that donation, but I think these will get us by for now.

**Comment by WebsByTodd** [comment]
Merged into master with #66
