### ISSUE TITLE
Get mytake ready for more open contributors

### ISSUE THREAD

**Issue by nedtwigg** [mytake/mytake#39]
- [x] code formatting #35
- [x] document the build in README
- [x] move mytake to a GitHub org
    - [x] Ping the mytake user
        - Will be better if we have fleshed out homepage (#38) and about (#37)
    - [x] If that fails, try GitHub support
    - ~~If that fails, mytake_org~~
- [x] hook into CI (depends on having the org)

**Comment by nedtwigg** [comment]
I think you had mentioned [netlify](https://www.netlify.com/) to me before, Todd.  It would be good if we could see pull requests without building, and the github pages workflow that we've been using doesn't make that easy.  I'm in favor of the following (we can discuss on next call, @WebsByTodd)

- delete the `docs` folder
- create an `npm build` task that builds the site and puts it into a `dist` folder
- add the `dist` folder to `.gitignore`
- make `npm build` build the site to the `dist` folder
- setup netlify to deploy all pull-requests
    - .nvmrc file to make sure we get the right version of node

There's some other stuff we should do to make it easier for contributors:

- [ ] [polish the package.json](https://docs.npmjs.com/files/package.json)
- [ ] update any errant `nedtwigg/mytake` references in the docs

**Comment by nedtwigg** [comment]
[ ] Migrate to GPL

**Comment by WebsByTodd** [comment]
- [ ] Create a CONTRIBUTING.md
- [ ] Create a CHANGELOG.md

Take a look at https://github.com/shayc/cboard for an open source project that was started about a month ago that's a bit more friendlier to new contributors than our current project.
