### ISSUE TITLE
Improve experience of reading a take vs writing it

### ISSUE THREAD

**Issue by nedtwigg** [mytake/mytake#40]
First experience of every user will be to read a take.  We should suck them into exploring the foundation, and into creating their own takes.

**Comment by WebsByTodd** [comment]
- Created a BlockReader component for this.
- HTML pages for reading Takes use the BlockReader component as the root React component.
- When Foundation blocks are clicked, user is redirected to a page with FoundationExplorer as the root React component.

See PR #52
