### ISSUE TITLE
Under construction

### ISSUE THREAD

**Issue by WebsByTodd** [mytake/mytake#65]
Need to add to our header an "under construction" notice with a link or two to useful information:

- How to use our MyTake prototype (e.g. can't save/share Takes currently).
- How to contribute financially.
- How to contribute from a technical standpoint.

**Comment by nedtwigg** [comment]
The "write your own take" page ought to have a "You can't save yet" warning banner.

**Comment by WebsByTodd** [comment]
PR #69  preview is available [here](https://deploy-preview-69--mytake.netlify.com/).

Regarding the header banner links, where do you want these pages to live? On GitHub or directly on the site on a new page or modal window?
 - How to use
 - Contributing (both financially and technically)

**Comment by nedtwigg** [comment]
No strong preference, my first instinct is `WORK_IN_PROGRESS.md` in GitHub.

**Comment by WebsByTodd** [comment]
#69
