### ISSUE TITLE
Fix "Mixed Content" warnings

### ISSUE THREAD

**Issue by WebsByTodd** [mytake/mytake#89]
We request images from YouTube in our news feed using http. Since we have https in our live production environment we need to request these using https. There should also be a way to set the environment variable NODE_ENV in our webpack config so we can load over http in a dev environment and https in production.

YouTube videos are also played on several routes of the site. Sometimes I see the [Failed to execute 'postMessage' on 'DOMWindow'](https://stackoverflow.com/questions/27573017/failed-to-execute-postmessage-on-domwindow-https-www-youtube-com-http) error message, which is also related to http vs. https. Look into this too.

**Comment by nedtwigg** [comment]
How about we always request external resources with https, and always refer to internal as path-only.  Does that let us avoid looking at NODE_ENV?

**Comment by WebsByTodd** [comment]
Maybe I was overthinking it. Your idea should work in this case. I was thinking that showing https stuff on http pages as not possible without warnings but it's only the other way around. And in this case, YouTube serves the same content over both http and https, so we're not breaking any security practices.

**Comment by nedtwigg** [comment]
I just checked - it's possible in netlify to force HTTPS, but I'm inclined to not do that until we've fixed the mixed-content warnings.

**Comment by WebsByTodd** [comment]
These are fixed in #90

**Comment by nedtwigg** [comment]
Great!  I enabled the checkbox to redirect all http to https.
